sonar.projectKey=loviiin_ponto-api-go
sonar.organization=loviiin

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/internal/config/seeder.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go configuration
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=report.json
