# Project Key (Deve ser único e SEM ESPAÇOS)
sonar.projectKey=loviiin_ponto-api-go

# Organization Key (A chave técnica da organização no SonarCloud, SEM ESPAÇOS)
sonar.organization=loviiin
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/internal/config/seeder.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go configuration
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=report.json
