sonar.projectKey=Guilherme Henrique De Souza Villa Real_ponto-api-go
sonar.organization=Guilherme Henrique De Souza Villa Real

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/internal/config/seeder.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go configuration
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=report.json
