package permissions

const (
	EDITAR_EMPRESA        = "EDITAR_EMPRESA"
	DELETAR_EMPRESA       = "DELETAR_EMPRESA"
	GERENCIAR_CARGOS      = "GERENCIAR_CARGOS"
	DELETAR_USUARIO       = "DELETAR_USUARIO"
	EDITAR_USUARIO        = "EDITAR_USUARIO" // <-- NOVA PERMISSÃO
	EDITAR_PROPRIA_CONTA  = "EDITAR_PROPRIA_CONTA"
	DELETAR_PROPRIA_CONTA = "DELETAR_PROPRIA_CONTA"
)
