package permissions

const (
	EDITAR_EMPRESA                = "EDITAR_EMPRESA"
	DELETAR_EMPRESA               = "DELETAR_EMPRESA"
	GERENCIAR_CARGOS              = "GERENCIAR_CARGOS"
	DELETAR_USUARIO               = "DELETAR_USUARIO"
	EDITAR_USUARIO                = "EDITAR_USUARIO"
	EDITAR_PROPRIA_CONTA          = "EDITAR_PROPRIA_CONTA"
	DELETAR_PROPRIA_CONTA         = "DELETAR_PROPRIA_CONTA"
	VER_SALDO_FUNCIONARIOS        = "VER_SALDO_FUNCIONARIOS"
	EDITAR_SALDO_FUNCIONARIOS     = "EDITAR_SALDO_FUNCIONARIOS"
	VISUALIZAR_PONTO_FUNCIONARIOS = "VISUALIZAR_PONTO_FUNCIONARIOS"
	AJUSTAR_PONTO_FUNCIONARIOS    = "AJUSTAR_PONTO_FUNCIONARIOS"
	GERENCIAR_JUSTIFICATIVAS      = "GERENCIAR_JUSTIFICATIVAS"
	VER_JUSTIFICATIVAS_PENDENTES  = "VER_JUSTIFICATIVAS_PENDENTES"
	CRIAR_JUSTIFICATIVA_PROPRIA   = "CRIAR_JUSTIFICATIVA_PROPRIA"
	APROVAR_JUSTIFICATIVAS        = "APROVAR_JUSTIFICATIVAS"
	GERENCIAR_LOCALIDADES         = "GERENCIAR_LOCALIDADES"
	VISUALIZAR_RELATORIOS_GERAIS  = "VISUALIZAR_RELATORIOS_GERAIS"
)
