package permissions

const (
	EDITAR_EMPRESA            = "EDITAR_EMPRESA"
	DELETAR_EMPRESA           = "DELETAR_EMPRESA"
	GERENCIAR_CARGOS          = "GERENCIAR_CARGOS"
	DELETAR_USUARIO           = "DELETAR_USUARIO"
	EDITAR_USUARIO            = "EDITAR_USUARIO"
	EDITAR_PROPRIA_CONTA      = "EDITAR_PROPRIA_CONTA"
	DELETAR_PROPRIA_CONTA     = "DELETAR_PROPRIA_CONTA"
	VER_SALDO_FUNCIONARIOS    = "VER_SALDO_FUNCIONARIOS"
	EDITAR_SALDO_FUNCIONARIOS = "EDITAR_SALDO_FUNCIONARIOS"
)
