// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/Loviiin/ponto-api-go/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Autentica um usuário com email e senha e retorna um token JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Realiza o login do usuário",
                "parameters": [
                    {
                        "description": "Credenciais de Login",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bancohoras/fechamento/usuario/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Calcula o saldo de horas de um dia para um usuário e o adiciona ao saldo total do banco de horas. Requer permissão 'EDITAR_SALDO_FUNCIONARIOS'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Banco de Horas"
                ],
                "summary": "Realiza o fechamento manual de um dia",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2025-08-26\"",
                        "description": "Dia para fechar (formato: AAAA-MM-DD)",
                        "name": "dia",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Usuario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bancohoras/saldo/usuario/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna o saldo de horas (positivo ou negativo) de um usuário para um dia específico. Requer permissão 'VER_SALDO_FUNCIONARIOS' se o ID consultado não for o do próprio usuário.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Banco de Horas"
                ],
                "summary": "Consulta saldo de horas do dia",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2025-08-26\"",
                        "description": "Dia para consulta (formato: AAAA-MM-DD)",
                        "name": "dia",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cargos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista de todos os cargos da empresa do usuário logado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cargos"
                ],
                "summary": "Lista os cargos da empresa",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Cargo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cria um novo cargo para a empresa do usuário logado. Requer permissão 'GERENCIAR_CARGOS'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cargos"
                ],
                "summary": "Cria um novo cargo",
                "parameters": [
                    {
                        "description": "Dados do novo cargo",
                        "name": "cargo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cargo.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Cargo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cargos/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza os dados de um cargo. Requer permissão 'GERENCIAR_CARGOS'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cargos"
                ],
                "summary": "Atualiza um cargo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Cargo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "dados",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deleta um cargo da empresa. Requer permissão 'GERENCIAR_CARGOS'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cargos"
                ],
                "summary": "Deleta um cargo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Cargo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cargos/{id}/permissoes/{permissaoId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Associa uma permissão existente a um cargo. Requer permissão 'GERENCIAR_CARGOS'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cargos"
                ],
                "summary": "Adiciona permissão a um cargo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Cargo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID da Permissão",
                        "name": "permissaoId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/empresas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista de todas as empresas cadastradas. Requer autenticação.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empresas"
                ],
                "summary": "Lista todas as empresas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Empresa"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Registra uma nova empresa no sistema e configura cargos e permissões padrão para ela.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empresas"
                ],
                "summary": "Cria uma nova empresa",
                "parameters": [
                    {
                        "description": "Dados da nova empresa",
                        "name": "empresa",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/empresa.criaEmpresaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Empresa"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/empresas/{id}": {
            "get": {
                "description": "Retorna os dados de uma empresa específica pelo seu ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empresas"
                ],
                "summary": "Busca uma empresa por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Empresa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Empresa"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza os dados de uma empresa. Requer permissão 'EDITAR_EMPRESA'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empresas"
                ],
                "summary": "Atualiza uma empresa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Empresa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "dados",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deleta uma empresa permanentemente. Requer permissão 'DELETAR_EMPRESA'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empresas"
                ],
                "summary": "Deleta uma empresa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Empresa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/justificativas": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Um funcionário cria uma solicitação para adicionar ou corrigir um registro de ponto.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Justificativas"
                ],
                "summary": "Solicita um ajuste de ponto",
                "parameters": [
                    {
                        "description": "Dados da solicitação de ajuste",
                        "name": "solicitacao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/justificativa.solicitarAjusteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Justificativa"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Falha interna no servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/justificativas/pendentes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista de todas as solicitações de ajuste de ponto que estão pendentes de aprovação. Requer permissão.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Justificativas"
                ],
                "summary": "(Admin) Lista justificativas pendentes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Justificativa"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/justificativas/{id}/processar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Processa uma solicitação de ajuste, aprovando-a (o que cria o registro de ponto) ou reprovando-a. Requer permissão.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Justificativas"
                ],
                "summary": "(Admin) Aprova ou reprova uma justificativa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Justificativa",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Ação de Aprovação/Reprovação",
                        "name": "acao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/justificativa.aprovarReprovarRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Justificativa"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permissoes": {
            "get": {
                "description": "(Admin) Retorna uma lista de todas as permissões disponíveis no sistema.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissões"
                ],
                "summary": "Lista todas as permissões",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Permissao"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "(Admin) Cria uma nova permissão global no sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissões"
                ],
                "summary": "Cria uma nova permissão",
                "parameters": [
                    {
                        "description": "Dados da nova permissão",
                        "name": "permissao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Permissao"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Permissao"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pontos": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra um evento de ponto (entrada/saída) para o usuário logado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ponto"
                ],
                "summary": "Registra uma batida de ponto",
                "parameters": [
                    {
                        "description": "Coordenadas da Batida de Ponto",
                        "name": "ponto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ponto.BaterPontoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.RegistroPonto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pontos/ajuste": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adiciona um novo registro de ponto para um funcionário com uma justificativa. Requer permissão 'AJUSTAR_PONTO_FUNCIONARIOS'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ponto"
                ],
                "summary": "(Admin) Adiciona um registro de ponto manual",
                "parameters": [
                    {
                        "description": "Dados do ajuste de ponto",
                        "name": "ajuste",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ponto.AjustePontoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.RegistroPonto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pontos/meus-registros": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista das batidas de ponto do usuário logado para um dia específico. Se o dia não for fornecido, retorna os do dia atual.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ponto"
                ],
                "summary": "Lista os registros de ponto do usuário",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"2025-08-26\"",
                        "description": "Dia para consulta (formato: AAAA-MM-DD)",
                        "name": "dia",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.RegistroPonto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pontos/usuario/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista das batidas de ponto de um usuário específico para um determinado dia. Requer permissão 'VISUALIZAR_PONTO_FUNCIONARIOS'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ponto"
                ],
                "summary": "(Admin) Lista os registros de ponto de um usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2025-08-26\"",
                        "description": "Dia para consulta (formato: AAAA-MM-DD)",
                        "name": "dia",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.RegistroPonto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pontos/{pontoId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Altera o timestamp de um registro de ponto existente, criando uma justificativa para a auditoria. Requer permissão 'AJUSTAR_PONTO_FUNCIONARIOS'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ponto"
                ],
                "summary": "(Admin) Edita um registro de ponto existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Registro de Ponto a ser editado",
                        "name": "pontoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novos dados para o registro de ponto",
                        "name": "edicao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ponto.EditarPontoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RegistroPonto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista de todos os usuários pertencentes à empresa do requisitante.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Lista todos os usuários da empresa",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Usuario"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo usuário (funcionário) no sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Cria um novo usuário",
                "parameters": [
                    {
                        "description": "Dados do Novo Usuário",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usuario.CriarUsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Usuario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usuarios/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna as informações detalhadas do usuário que está a fazer o pedido.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Obtém os dados do usuário logado",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Usuario"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usuarios/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna os dados de um usuário específico da mesma empresa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Busca um usuário por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Usuario"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza os dados de um usuário. O corpo do pedido pode conter qualquer um dos campos definidos no modelo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Atualiza um usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Usuário a ser atualizado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "dados",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usuario.UpdateUsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deleta um usuário. Requer permissão de 'DELETAR_USUARIO' ou 'DELETAR_PROPRIA_CONTA'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuários"
                ],
                "summary": "Deleta um usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Usuário a ser deletado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "superadmin@ponto.com"
                },
                "password": {
                    "type": "string",
                    "example": "superadmin"
                }
            }
        },
        "cargo.createRequest": {
            "type": "object",
            "required": [
                "empresa_id",
                "nome"
            ],
            "properties": {
                "empresa_id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "empresa.criaEmpresaRequest": {
            "type": "object",
            "required": [
                "nome",
                "raioGeofenceMetros",
                "sedeLatitude",
                "sedeLongitude"
            ],
            "properties": {
                "nome": {
                    "type": "string"
                },
                "raioGeofenceMetros": {
                    "type": "number"
                },
                "sedeLatitude": {
                    "type": "number"
                },
                "sedeLongitude": {
                    "type": "number"
                }
            }
        },
        "justificativa.aprovarReprovarRequest": {
            "type": "object",
            "properties": {
                "aprovado": {
                    "type": "boolean"
                },
                "motivo_reprovacao": {
                    "type": "string"
                }
            }
        },
        "justificativa.solicitarAjusteRequest": {
            "type": "object",
            "required": [
                "data_ocorrencia",
                "descricao",
                "tipo"
            ],
            "properties": {
                "data_ocorrencia": {
                    "type": "string",
                    "example": "2025-09-10T09:00:00Z"
                },
                "descricao": {
                    "type": "string",
                    "example": "Esqueci de bater o ponto na entrada."
                },
                "tipo": {
                    "type": "string",
                    "example": "ENTRADA_ESQUECIDA"
                }
            }
        },
        "model.Cargo": {
            "type": "object",
            "properties": {
                "carga_horaria_diaria_minutos": {
                    "type": "integer"
                },
                "empresa_id": {
                    "type": "integer"
                },
                "entrada_esperada_minutos": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "minutos_almoco_esperado": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "permissoes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Permissao"
                    }
                },
                "saida_esperada_minutos": {
                    "type": "integer"
                }
            }
        },
        "model.Empresa": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "raioGeofenceMetros": {
                    "type": "number"
                },
                "sedeLatitude": {
                    "type": "number"
                },
                "sedeLongitude": {
                    "type": "number"
                }
            }
        },
        "model.Justificativa": {
            "type": "object",
            "properties": {
                "aprovador_id": {
                    "type": "integer"
                },
                "data_ocorrencia": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "empresa_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "observacao_aprovador": {
                    "description": "Para feedback ou motivo da reprovação",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "usuario_id": {
                    "type": "integer"
                }
            }
        },
        "model.Permissao": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "model.RegistroPonto": {
            "type": "object",
            "properties": {
                "data_criacao": {
                    "type": "string"
                },
                "empresa_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "justificativa": {
                    "description": "Opcional, para carregar os dados se necessário",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Justificativa"
                        }
                    ]
                },
                "justificativa_id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "localizacao": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "metodo": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "usuario_id": {
                    "type": "integer"
                }
            }
        },
        "model.Usuario": {
            "type": "object",
            "properties": {
                "cargo_id": {
                    "type": "integer"
                },
                "data_atualizacao": {
                    "type": "string"
                },
                "data_criacao": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "empresa_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "saldo_banco_horas_minutos": {
                    "type": "integer"
                }
            }
        },
        "ponto.AjustePontoRequest": {
            "type": "object",
            "required": [
                "justificativa",
                "timestamp",
                "usuario_id"
            ],
            "properties": {
                "justificativa": {
                    "type": "string",
                    "example": "Ajuste manual de entrada."
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-09-10T09:00:00Z"
                },
                "usuario_id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "ponto.BaterPontoRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": -15.799879
                },
                "longitude": {
                    "type": "number",
                    "example": -47.864162
                }
            }
        },
        "ponto.EditarPontoRequest": {
            "type": "object",
            "required": [
                "justificativa",
                "timestamp"
            ],
            "properties": {
                "justificativa": {
                    "type": "string",
                    "example": "Correção do horário de saída."
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-09-10T18:05:00Z"
                }
            }
        },
        "usuario.CriarUsuarioRequest": {
            "type": "object",
            "required": [
                "cargo_id",
                "email",
                "empresa_id",
                "nome",
                "senha"
            ],
            "properties": {
                "cargo_id": {
                    "type": "integer",
                    "example": 2
                },
                "email": {
                    "type": "string",
                    "example": "joao.silva@empresa.com"
                },
                "empresa_id": {
                    "type": "integer",
                    "example": 1
                },
                "nome": {
                    "type": "string",
                    "example": "João Silva"
                },
                "senha": {
                    "type": "string",
                    "minLength": 6,
                    "example": "senha123"
                }
            }
        },
        "usuario.UpdateUsuarioRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao.dasilva@empresa.com"
                },
                "nome": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "senha": {
                    "type": "string",
                    "example": "novaSenha456"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Digite 'Bearer' seguido de um espaço e o seu token.\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Ponto API em Go",
	Description:      "API de alta performance para um sistema de Ponto Eletrônico.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
